version: '3.4'

services:
  tashansofrasi.db:
    environment:
      - SA_PASSWORD=Passw@rd1.
      - ACCEPT_EULA=Y
    volumes:
    - tashansofrasi.db-volume:/var/opt/mssql
    ports:
      - "1433:1433"
  tashansofrasi.signalrapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - DB_HOST=tashansofrasi.db
      - DB_NAME=TashanSofrasiDB
      - DB_SA_PASSWORD=Passw@rd1.
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ./Https:/Https:ro
  tashansofrasi.webapp:
   environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8082
      - ASPNETCORE_HTTPS_PORTS=8083
      - DB_HOST=tashansofrasi.db
      - DB_NAME=TashanSofrasiDB
      - DB_SA_PASSWORD=Passw@rd1.
   ports:
      - "8082:8082"
      - "8083:8083"
   volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ./Https:/Https:ro