version: '3.4'

services:
  tashansofrasi.db:
    container_name: tashansofrasi.db-container
    image: burakarslan0110/tashansofrasidb-image:v1
  tashansofrasi.signalrapi:
    container_name: tashansofrasi.signalrapi-container
    image: tashansofrasisignalrapi-image
    build:
      context: .
      dockerfile: TashanSofrasiSignalRApi/Dockerfile
    depends_on:
    - tashansofrasi.db
  tashansofrasi.webapp:
    container_name: tashansofrasi.webapp-container
    image: tashansofrasiwebapp-image
    build:
      context: .
      dockerfile: TashanSofrasiWebApp/Dockerfile
    depends_on:
      - tashansofrasi.signalrapi
      - tashansofrasi.db
volumes:
  tashansofrasi.db-volume:
   